### NumPy的多维数组


In [8]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape)
print(A.dtype) 
B = np.array([[3, 0], [0, 6]])
C = A + B
print(C)
print(A*B)

D = np.array([[10, 20]])
print("A" + "*" + "D")
print(A*D)

[[1 2]
 [3 4]]
(2, 2)
int32
[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]
A*D
[[10 40]
 [30 80]]


#### NumPy数组元素访问


In [12]:
X = np.array([[52, 55], [14, 19], [0, 4]])
print(X)
print(X[0])
print(X[0][1])

for row in X:
    print(row)

X = X.flatten()
print(X)

print(X[np.array([0, 2, 4])])

print(X > 15)
print(X[X > 15])


[[52 55]
 [14 19]
 [ 0  4]]
[52 55]
55
[52 55]
[14 19]
[0 4]
[52 55 14 19  0  4]
[52 14  0]
[ True  True False  True False False]
[52 55 19]
